### ISSUE TITLE
[Idee] Maus auf Domäne Fenster mit mehr Infos

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/md-fw-dl#10]
Moin,

ich hatte die Idee, ob man nicht noch in einer Art kleinem Fester mehr Infos wie z. B. die Portnummer und die eingesetzt VPN-Technologie anzeigen könnte, wenn man die Maus auf der Karte auf eine Domäne hält.

So, wie es früher mit der Karte auf firmware.freifunk-muensterland.de war.

Grüße

**Comment by descilla** [comment]
Ja, die Karte auf firmware.freifunk-muensterland.org soll ja von uMap auf eine eigene Implementation umgestellt werden. Dort sollen genau solche Informationen dargestellt werden. Man könnte das im Anschluss backporten. Siehe: https://forum.freifunk-muensterland.de/t/karte-beim-firmewaredownload-updaten-bitte/1116/9?u=descilla

**Comment by christian-weiss** [comment]
Aus Anwender-Sicht: 
Sind VPN-Technologie und Portnummer relevant?

Wenn es darum geht mit den Freifunk-Knoten der Nachbarschaft zu meshen, dann muss man in die selbe Domäne wie die Nachbarn haben und nehmen was in der Domäne Phase ist.

Nur wenn man nicht vor hat zu meshen, dann kann man selbst eine "Technologie-Entscheidung" treffen und sich in weiter entfernten Domänen mit einer anderen Firmware versorgen. Ist das ein Fall den wir derart nutzerfreundlich supporten möchten? (Ich frag ja nur, ... vermutlich gibt es Dinge, die mehr Sinn für das Projekt ergeben - die knappe Freizeit die wir investieren können im Blick). 

Oder übersehe ich hier einen Punkt?

**Comment by descilla** [comment]
Es geht eher darum, dass man beim Download der richtigen Firmware direkt alle Parameter zur Hand, die man zum Einrichten ggf. Benötigt. Beispielsweise den VPN-Port, wenn der Knoten hinter einer restriktiven Firewall steht.

**Comment by MPW1412** [comment]
Das Ticket ist von 2016. Mouseover ist der Mobile-First-Strategie zum Opfer gefallen. Meiner Meinung nach kann das hier zu.

**Comment by christian-weiss** [comment]
Der Firmware Download Assistent soll dem Anwender helfen die richtige Firmware-Datei für seinen Router zu finden. Welcher Port hinterher beim Einrichten der Firewall zu verwenden ist, ist m.E. ein Kriterium bei der Auswahl des richtigen Firmware-Images, und muss daher nicht im Auswahl-Prozess angezeigt werden (egal ob per MouseOver oder anderswie). 

Nach dem Download bzw. nach der Auswahl kann man m.E. noch weitere Hilfestellung wie Protokoll und Port (für die Firewall-Konfiguration) anzeigen. Ich habe das mal als Ticket #29 erstellt.

Persönlich finde ich aber dass dieses in die Installations-Anleitung gehört. Ich würde diese Ticket hier auch gerne schließen. @MPW1412 kannst Du das machen?
