### ISSUE TITLE
Karte auf firmware.freifunk-muensterland.de aktualisieren

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/md-fw-dl#12]
Moin,

die Karte auf der Startseite passt nicht mehr zu der im Firmwaredownloader. Die müsste aktualisiert werden und die Beschreibungen der Domänen hinzugefügt werden.

http://firmware.freifunk-muensterland.org/
versus
http://firmware.freifunk-muensterland.org/md-fw-dl

Grüße
Matthias

**Comment by descilla** [comment]
Die Karte soll neu gemacht werden. Zwischenzeitlich soll sie entfernt werden, damit es nicht zu verschiedenen Ständen kommt. Siehe: https://forum.freifunk-muensterland.de/t/karte-beim-firmewaredownload-updaten-bitte/1116/7?u=descilla

Die Webseite wird über Ansible generiert ( https://github.com/FreiFunkMuenster/ansible-ffms/blob/master/roles/firmware_web/templates/index.html.j2 ). Bitte dort ein Ticket aufmachen.
