### ISSUE TITLE
Selm hinzufügen

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/md-fw-dl#14]
Die Freifunker aus Selm haben sich dem Freifunk Münsterland und der Domäne 02 angeschlossen. Das sollte auf der Karte so festgehalten werden.

Dazu müsste ein Polygon erstellt werden, das dann auf die Domäne 02 verlinkt. 

http://www.freifunk-selm.de/2016/05/08/domaenenwechsel/

**Comment by descilla** [comment]
Hinzugefügt und ausgerollt.

**Comment by MPW1412** [comment]
Da hatte ich gerade angekündigt, dass das länger dauert und du machst hier wieder Nachtschicht. :P 

Danke dir!

**Comment by kgbvax** [comment]
Wurde das mit "Selm angeschlossen" irgendwo diskutiert?

**Comment by MPW1412** [comment]
Nein, in keinster Weise. Die haben das einfach mal so entschieden und auch schon alle ihre Knoten umgezogen: https://karte.freifunk-muensterland.org/map02/. Ich wusste davon bis vorhin nichts.

Ich habe ihnen heute mal eine Willkommensemail geschickt und auf ein paar Dinge hingewiesen.

Ich hoffe, dass sie sich melden und mal vorstellen.
