### ISSUE TITLE
Legende unterlappt Rand

### ISSUE THREAD

**Issue by ghost** [FreiFunkMuenster/md-fw-dl#19]
Leider ist nicht die komplette Legende auf der rechten Seite sichtbar. Da die Liste sehr lang geworden ist, unterlappt sie den oberen Rand.

Ich glaube man nennt die fehlende Funktion 'responsivity'...

**Comment by descilla** [comment]
@MPW1412 und ich haben schon darüber gesprochen. Der Plan ist die Legende rauszuwerfen und durch einen Hinweis zu ersetzen, dass man die Polygone anklicken soll. Zusätzlich soll beim Hover über die Polygone der Name der jeweiligen Domäne erscheinen. (Da ich derzeit keine Zeit habe, unassigne ich das mal von mir.)
