### ISSUE TITLE
Legende alphabetisch sortieren

### ISSUE THREAD

**Issue by ghost** [FreiFunkMuenster/md-fw-dl#20]
Zurzeit ist die Liste der Domänen in der Legende nicht alphabetisch sortiert. Dadurch wird das Auffinden von einzelnen Domänen erschwert.

**Comment by descilla** [comment]
Die Sortierung entspricht der Sortierung unter dem Dropdown "Bitte wähle einen Ort", was durchaus sinnig ist hier stringent zu sein. Daher sollten wir über die Sortierung im Dropdown sprechen (Die im Übrigen der Domänen-ID nach sortiert sind). Zum einen leitet sich dann hieraus die Sortierung der Legende ab, zum anderen soll die Legende eh abgeschafft werden (siehe Issue #19 ).
