### ISSUE TITLE
Farbe des Borkener Polygons

### ISSUE THREAD

**Issue by ghost** [FreiFunkMuenster/md-fw-dl#21]
Die Farbe des Borkener Polygons unterscheidet sich leider nicht genug von der umliegenden Fläche (Westmünsterland). Empfehlung: Knatschgelb.

**Comment by descilla** [comment]
In Zeile 7 in [diesem](https://github.com/FreiFunkMuenster/md-fw-dl/blob/master/map.js) Dokument wird ein Array von Farben definiert, die der Reihe nach verwendet werden. Wenn alle Farben "aufgebraucht" sind, wird wieder von vorne begonnen. Es könnten also einfach mehr Farben hinzugefügt werden. Leider ist mir da die Kreativität abhanden gekommen. Hast du Lust neue Farben zu finden und dort einzutragen?

**Comment by ghost** [comment]
Ich werde morgen mal mein bestes versuchen.

**Comment by ghost** [comment]
Wenn ich das nun richtig verstehe, gibt es 18 verschiedene Farben. Westmünsterland ist Domäne 06, Borken ist Domäne 26. 18+6 ist aber 24. Dann müssten die doch unterschiedliche Farben haben, oder irre ich mich gewaltig in meiner Rechnung?

Ansonsten dürfte es ja wohl reichen, eine weitere Farbe zu ändern. Dann verschiebt sich ab Domäne 19 alles um einen Schritt. Dann kann es aber sein, dass an anderen Stellen, sich die Farben gleichen.
